### ISSUE TITLE
KeyError: "No object named 'SalMSDataModule' found in 'data_module' registry!"

### ISSUE THREAD

**Issue by blingsr** [hanlinwu/SalDRN#2]
(SaIDRN) chenz@chenz-System-Product-Name:/media/chenz/500G/SalDRN$ python train.py --config /media/chenz/500G/SalDRN/config/sal_cssr_epsilon_fb.yaml
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    train_pipeline(args)
  File "train.py", line 62, in train_pipeline
    datamodule = create_data_module(config.data_module)
  File "/media/chenz/500G/SalDRN/litsr/data/__init__.py", line 31, in create_data_module
    data_module = DataModuleRegistry.get(data_module_name)
  File "/media/chenz/500G/SalDRN/litsr/utils/registry.py", line 67, in get
    raise KeyError(
KeyError: "No object named 'SalMSDataModule' found in 'data_module' registry!"

**Comment by B-7** [comment]
hey @blingsr ! I had the same problem recently. I solved the problem by copying `data/sal_datamodule.py` and related files from `data/` to `litsr/data/`.
